name: wallet_apps
description: A new Flutter project. 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.16+39
#6 feature
#8 debug
#1 refactor
#last 8 build
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  
  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
  geolocator: ^5.3.2+2

  url_launcher: ^6.0.3
  
  latlong: ^0.6.1
  web_socket_channel:

  webview_flutter: ^1.0.7

  gsheets:
  
  # Database
  shared_preferences:

  # Backend
  http: 
  connectivity:
  connectivity_wrapper:
  async:

  # Image service

  flutter_svg:
  intl:

  # Camera
  qr_flutter: 
  qr_code_scanner:

  # Chart
  flutter_circular_chart:
  charts_flutter:
  fl_chart:
  pie_chart:

  #Indicator
  percent_indicator:

  # Icons
  line_awesome_flutter:
  pinput: ^1.0.0
  transparent_image:  
  date_format:
 
  store_redirect:
  share:

  vibration: ^1.7.3
 
  # Apps Configuration
  rename:
  package_info: 
  shimmer: ^1.1.2

  # Authentication & Verification
  local_auth: ^1.1.6
  permission_handler:

  #for secure wallet function

  polkawallet_sdk:
    path: ../
  animations:
  provider:
  web3dart: 
  bitcoin_flutter:

  flutter_secure_storage:
  flutter_screenshot_switcher: ^1.2.0

  #Contact
  contacts_service: ^0.4.6 
  fluttercontactpicker: 
  
  #animation
  flare_flutter:
  responsive_framework: ^0.0.8
  circular_check_box: ^1.0.4
  flutter_launcher_icons: ^0.8.1
  timeline_tile:
  flutter_secure_storage_web: ^1.0.2
  passcode_screen: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.3.2

  # run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#F5F5F5"
  color_dark: "#090D28"
  
  image: assets/img_edgeware_primary.png
  android: true
  ios: true
 

# Run command: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  image_path: "assets/ic_launcher.png"
  ios: true
  android: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/abi/
    - assets/icons/
  

    # Animation Flare
    - assets/animation/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Roman.otf
        
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  #module: 
   # androidX: true
